version: '3.8'

services:
  # Servicio 1: La Base de Datos (MySQL)
  metafit-db:
    image: mysql:8.0
    container_name: metafit_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metafit_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Servicio 2: El gestor visual (phpMyAdmin)
  metafit-phpmyadmin:
    image: phpmyadmin:latest
    container_name: metafit_phpmyadmin
    restart: always
    links:
      - metafit-db:db
    ports:
      - "8085:80"
    environment:
      PMA_HOST: metafit-db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  db_data: