-- MetaFit v2.0 — Migración: Seguimiento diario app móvil
-- Tablas para progreso diario de ejercicios y registro de agua

CREATE TABLE IF NOT EXISTS PROGRESO_EJERCICIO_DIARIO (
  id_progreso INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  id_usuario  INT UNSIGNED NOT NULL,
  id_ciclo    INT UNSIGNED NOT NULL,
  id_ejercicio INT UNSIGNED NOT NULL,
  fecha       DATE NOT NULL,
  completado  TINYINT(1) NOT NULL DEFAULT 0,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ejercicio_dia (id_usuario, id_ciclo, id_ejercicio, fecha),
  FOREIGN KEY (id_usuario)  REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
  FOREIGN KEY (id_ciclo)    REFERENCES CICLO(id_ciclo) ON DELETE CASCADE,
  FOREIGN KEY (id_ejercicio) REFERENCES EJERCICIO(id_ejercicio) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS REGISTRO_AGUA (
  id_agua     INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  id_usuario  INT UNSIGNED NOT NULL,
  fecha       DATE NOT NULL,
  vasos       TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_agua_dia (id_usuario, fecha),
  FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CONSUMO_ALIMENTO_DIARIO (
  id_consumo  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  id_usuario  INT UNSIGNED NOT NULL,
  id_ciclo    INT UNSIGNED NOT NULL,
  id_alimento INT UNSIGNED NOT NULL,
  num_comida  TINYINT UNSIGNED NOT NULL,
  fecha       DATE NOT NULL,
  consumido   TINYINT(1) NOT NULL DEFAULT 0,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_alimento_dia (id_usuario, id_ciclo, id_alimento, num_comida, fecha),
  FOREIGN KEY (id_usuario)  REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
  FOREIGN KEY (id_ciclo)    REFERENCES CICLO(id_ciclo) ON DELETE CASCADE,
  FOREIGN KEY (id_alimento) REFERENCES ALIMENTO(id_alimento) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
